In [36]:
import pandas as pd
import ast

df = pd.read_csv('../datas/movies_metadata.csv')

C:\Users\feldm\AppData\Local\Temp\ipykernel_12228\4091169607.py:4: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../datas/movies_metadata.csv')

In [32]:
df['vote_count'].mean()

109.89733831940167

In [37]:

# get genres in a list
df.genres = df.genres.apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
df.genres = df.genres.apply(lambda x: [genre['name'] for genre in x])
# change some type
df = df.astype({'title':'string'})
# clean 
df = df.dropna(subset=['title','overview','vote_count'])
# change types
df['id'] = df['id'].astype('int64')
df['release_date'] = pd.to_datetime(df['release_date'])
# get rid of weird values
df = df.loc[(df['vote_count']) > (100)]
# creation of a year column 
df['year'] = df['release_date'].dt.year
# deleting useless col
df = df.drop(['status','original_title','homepage','belongs_to_collection'], axis=1)

df['budget'] = df['budget'].astype('int64')
df['overview'] = df['overview'].astype('str')

In [43]:
links = pd.read_csv("../datas/links.csv")

df.rename(columns = {'id':'tmdbId'}, inplace = True)
test = pd.merge(links,df, on='tmdbId',how='inner')
test.drop(['imdbId'], axis=1)
test = test.set_index('movieId')

test

,imdbId,tmdbId,adult,budget,genres,imdb_id,original_language,overview,popularity,poster_path,...,release_date,revenue,runtime,spoken_languages,tagline,title,video,vote_average,vote_count,year
movieId,,,,,,,,,,,,,,,,,,,,,
1,114709,862.0,False,30000000,"[Animation, Comedy, Family]",tt0114709,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",NaN,Toy Story,False,7.7,5415.0,1995
2,113497,8844.0,False,65000000,"[Adventure, Fantasy, Family]",tt0113497,en,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,1995
5,113041,11862.0,False,0,[Comedy],tt0113041,en,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,1995
6,113277,949.0,False,60000000,"[Action, Crime, Drama, Thriller]",tt0113277,en,"Obsessive master thief, Neil McCauley leads a ...",17.924927,/zMyfPUelumio3tiDKPffaUpsQTD.jpg,...,1995-12-15,187436818.0,170.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",A Los Angeles Crime Saga,Heat,False,7.7,1886.0,1995
7,114319,11860.0,False,58000000,"[Comedy, Romance]",tt0114319,en,An ugly duckling having undergone a remarkable...,6.677277,/jQh15y5YB7bWz1NtffNZmRw0s9D.jpg,...,1995-12-15,0.0,127.0,"[{'iso_639_1': 'fr', 'name': 'Fran√ßais'}, {'is...",You are cordially invited to the most surprisi...,Sabrina,False,6.2,141.0,1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175795,5117876,417320.0,False,0,"[TV Movie, Family, Action, Comedy, Music, Adve...",tt5117876,en,When the pressure to be royal becomes too much...,15.842073,/7TLywOVzWwU1GMyqdjUiSVzBiyc.jpg,...,2017-07-21,0.0,111.0,"[{'iso_639_1': 'da', 'name': 'Dansk'}]",Long live evil.,Descendants 2,False,7.5,171.0,2017
175823,4531694,277839.0,False,5402000,[Comedy],tt4531694,fr,Franky and Krimo dream of leaving the grey gri...,5.613875,/p7TFdcE2E9aqwqKMxQEPZZxDjv8.jpg,...,2016-02-24,0.0,100.0,"[{'iso_639_1': 'fr', 'name': 'Fran√ßais'}]",NaN,"Good Guys Go to Heaven, Bad Guys Go to Pattaya",False,5.3,153.0,2016
175995,2441982,248705.0,False,25868826,[Comedy],tt2441982,fr,"Stuck in the corridors of time, Godefroy de Mo...",7.29492,/2tR5dfWONNPCjW3Th2RFk2DuLsY.jpg,...,2016-03-23,0.0,110.0,"[{'iso_639_1': 'fr', 'name': 'Fran√ßais'}]",NaN,The Visitors: Bastille Day,False,4.0,167.0,2016
176211,6969946,455661.0,False,0,"[Family, Animation, Romance, Comedy]",tt6969946,en,A closeted boy runs the risk of being outed by...,20.82178,/wJUJROdLOtOzMixkjkx1aaZGSLl.jpg,...,2017-06-01,0.0,4.0,"[{'iso_639_1': 'en', 'name': 'English'}]",The Heart Wants What The Heart Wants,In a Heartbeat,False,8.3,146.0,2017
176219,294425,14008.0,False,0,[Comedy],tt0294425,en,Hyperactive teenager Kelly is enrolled into a ...,4.392389,/9sQVYo7B9cSexWXoQVzFFijCbD2.jpg,...,2002-03-07,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Too Cool For The Rules!,Cadet Kelly,False,5.2,145.0,2002

In [44]:
test.to_csv('../cleaned_data/cleaned_movies.csv')